<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "booking"
 *
 * Auto generated by Extension Builder 2020-02-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Booking',
    'description' => 'Booking extension for FE users',
    'category' => 'plugin',
    'author' => 'Joachim Ruhs',
    'author_email' => 'postmaster@joachim-ruhs.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
